GameTest Framework
Les-Moddeurs-Francais/Documentation-Forge pull request #101
Opened 2022-03-27 13:18 UTC by Mireole

# Pages sur le GameTest Framework
3 pages sur le GameTest Framework, une sur le framework en général, une sur les Batch(pour grouper les tests) et une autre sur les GameTestGenerator (nom explicite je pense)
## Page 1 : Utilisation du framework en général
![gametest_page_1](https://user-images.githubusercontent.com/83138584/160283236-19004f64-c00b-4427-bcc8-e57a238d82e2.png)

## Page 2 : Utilisation des Batch pour grouper des tests
![gametest_page_2](https://user-images.githubusercontent.com/83138584/160283243-133a37d8-57c4-4d99-9b8d-c0db4a8f28bf.png)

##Page 3 : Les GameTestGenerator
![gametest_page_3](https://user-images.githubusercontent.com/83138584/160283249-cee4c423-6cca-4c29-97be-7c516b3e9a11.png)

2022-03-27 13:28 UTC, Mysterious-Dev reviewed
Peut être déplacer le dossier gametests dans advanced (pour ne pas recréer une catégorie de plus mais une "sous catégorie")

2022-03-27 13:29 UTC, Mireole commented
OK

2022-03-27 13:34 UTC, Mireole commented
![image](https://user-images.githubusercontent.com/83138584/160284069-a6007ca0-3be4-4400-a53b-5d48832e283f.png)

2022-03-27 13:36 UTC, Mysterious-Dev commented on docs/gametests/gametest-framework.md
> +(La taille, la largeur et la profondeur de la structure sont des valeurs optionnelles)
La taille ?? Plutôt la longueur au vu de la commande précedente

2022-03-27 13:36 UTC, Mysterious-Dev commented on docs/gametests/gametest-framework.md
> +Pour lancer les tests et vérifier leur bon fonctionnement, vous avez deux solutions :
Plutôt _Pour lancer les tests et vérifier leurs bons fonctionnements, vous avez deux solutions :_ ?

2022-03-27 13:36 UTC, Mysterious-Dev commented on docs/gametests/gametest-framework.md
> +Si un test succède, un beacon vert apparaîtra proche de la template.
_Si un test est un succès_ ?

2022-03-27 13:39 UTC, Mysterious-Dev commented
Peut-être renomme le fichier `les_batch.md` en `batches`

2022-03-27 13:40 UTC, Mysterious-Dev approved these changes
Peut-être renommer le fichier `les_batch.md` en `batches.md`

2022-03-27 13:40 UTC, Mysterious-Dev commented
Merde me suis trompé de séléction...

2022-03-27 13:48 UTC, Mysterious-Dev requested changes

2022-03-27 13:48 UTC, Mysterious-Dev commented on docs/advanced/gametests/gametest-framework.md
> +tags: [GameTest]
Plutôt `game_test` que `GameTest` pour le tag

2022-03-27 13:48 UTC, Mysterious-Dev commented on docs/advanced/gametests/batches.md
> +tags: [GameTest]
Plutôt `game_test` que `GameTest` pour le tag

2022-03-27 13:48 UTC, Mysterious-Dev commented on docs/advanced/gametests/gametest_generator.md
> +tags: [GameTest]
Plutôt `game_test` que `GameTest` pour le tag

2022-03-27 13:50 UTC, Mireole commented
Les tags ont été changés

2022-03-27 13:56 UTC, Mysterious-Dev requested changes

2022-03-27 13:56 UTC, Mysterious-Dev commented on docs/advanced/gametests/gametest-framework.md
> +(La taille, la largeur et la profondeur de la structure sont des valeurs optionnelles)
La taille ?? Plutôt la longueur au vu de la commande précedente

2022-03-27 13:56 UTC, Mysterious-Dev commented on docs/advanced/gametests/gametest-framework.md
> +Pour lancer les tests et vérifier leur bon fonctionnement, vous avez deux solutions :
Plutôt _Pour lancer les tests et vérifier leurs bons fonctionnements, vous avez deux solutions :_ ?

2022-03-27 14:32 UTC, Mysterious-Dev commented on docs/advanced/gametests/_category_.json
> +  "position": 15
Peut-être changer la position pour 4

2022-03-27 14:35 UTC, Mysterious-Dev reviewed
Peut-être renommer gametest-framework.md ->framework.md et gametest_generator.md -> generator.md pour plus d'unicité avec les URL des autres catégories (éviter de répéter les mots dans l'URL)

2022-03-29 07:22 UTC, Mysterious-Dev commented on docs/advanced/gametests/framework.md
> +L'implémentation de ce système pour les moddeurs ayant été ajoutée dans dans Forge 39.0.88, vous devez être dans une version supérieure ou égale à celle-ci pour l'utiliser. (Je vous invite cependant
Mettre le . après la parenthèse (plus logique)

2022-03-29 07:22 UTC, Mysterious-Dev commented on docs/advanced/gametests/framework.md
> +Vous devez aussi vérifier que pour chaque configuration de run dans votre build.gradle, vous avez bien la ligne `property 'forge.enabledGameTestNamespaces', 'votre_mod_id'`. Cette ligne active tous l
_Chaque configuration de lancement_ non (question à débattre) ?

_vous avez bien la ligne `property 'forge.enabledGameTestNamespaces', 'votre_mod_id'`. Cette ligne active tous les tests liés à votre modid._ -> _vous avez bien la ligne suivante `property 'forge.enabledGameTestNamespaces', 'votre_mod_id'`, celle-ci activant tous les tests liés à votre modid._ ?

2022-03-29 07:22 UTC, Mysterious-Dev commented on docs/advanced/gametests/framework.md
> +Enfin, si vous ne l'avez pas, je vous invite à ajouter la configuration de run `runGameTestServer` avec les autres, qui va lancer un serveur sur votre ordinateur qui va exécuter tous les tests puis s
_qui va lancer un serveur sur votre ordinateur qui va exécuter tous les tests puis se fermer._ -> _celle-ci va lancer un serveur sur votre ordinateur qui va exécuter tous les tests puis se fermer._ ?

2022-03-29 07:22 UTC, Mysterious-Dev commented on docs/advanced/gametests/framework.md
> +Le nom du test n'est pas important, car il devra être changé plus tard de toute façon.
Pas forcement d'accord. Celui-ci est normalement important car il est aussi stocké dans le structure block (après je ne sais pas si tu as fait des tests pour vérifier cela (je peux me tromper aussi)).

2022-03-29 13:05 UTC, ZomDev3343 approved these changes
Les pages sont bien écrites, pour moi c'est bon.

2022-03-29 16:02 UTC, Mireole commented on docs/advanced/gametests/framework.md
> +Le nom du test n'est pas important, car il devra être changé plus tard de toute façon.
Lorsque la template est posée (pour les tests pas exemple, il reprend le nom du fichier donc change celui stocké dans le structure block, qui n'est d'ailleurs pas inclus dans la template si c'est bien la question (j'ai peut-être mal compris)

2022-03-29 16:14 UTC, Mireole commented on docs/advanced/gametests/framework.md
> +Vous devez aussi vérifier que pour chaque configuration de run dans votre build.gradle, vous avez bien la ligne `property 'forge.enabledGameTestNamespaces', 'votre_mod_id'`. Cette ligne active tous l
pour configuration de lancement effectivement j'aurais dû traduire effectivement je pense, je change ça tout de suite

2022-03-29 17:00 UTC, Mysterious-Dev commented on docs/advanced/gametests/framework.md
> +Le nom du test n'est pas important, car il devra être changé plus tard de toute façon.
C'est un truc à tester, je regarderais de mon coté et je te redirais.

2022-03-31 16:36 UTC, Mysterious-Dev approved these changes

2022-03-31 16:36 UTC, merged