Tags List
Les-Moddeurs-Francais/Documentation-Forge pull request #125
Opened 2022-05-22 12:10 UTC by Mysterious-Dev

2022-05-22 12:26 UTC, knightmar commented
Pour le mineable/hoe, ce n'est pas une faux mais une houe

2022-05-22 12:29 UTC, knightmar commented
Pour le candle_cakes, il manque un ^ sur le a de gâteau

2022-05-22 12:31 UTC, knightmar commented
Pour copper_ores, il faut traduire minerais de copper en minerais de cuivre

2022-05-22 12:33 UTC, knightmar commented
pour corals et coral_blocks, même description, il faudrait rajouter entre parenthèses ce une précision comme pour coral_plants

2022-05-22 12:35 UTC, knightmar commented
pour fall_damage_resetting, ce n'est pas "reinitialises" mais "réinitialisent"

2022-05-22 12:38 UTC, knightmar commented
pour prevent_mob_spawning_inside, il faut mettre empêchent au lieu de empêches

2022-05-22 12:41 UTC, knightmar commented
pour freeze_immune_entity_types, c'est gèlent au lieu de gèle

2022-05-22 12:42 UTC, knightmar commented
pour le moment, j'ai lu jusqu'à avant les items

2022-05-23 18:26 UTC, ZomDev3343 commented on docs/bases/resources/tags.md
> +| `beacon_base_blocks`                       | Liste des blocs qui peuvent activer une balise selon une structure pré-définit
prédéfinie*

2022-05-23 18:29 UTC, ZomDev3343 commented on docs/bases/resources/tags.md
> +| `animals_spawnable_on`                     | Liste des blocs sur lesquels les animaux peuvent apparaitre
remplacer tous les apparaitre par apparaître

2022-05-23 18:31 UTC, ZomDev3343 commented on docs/bases/resources/tags.md
> +| `has_structure\buried_treasure`        | Liste des biomes pouvant contenir des trésors enfuis                   |
enfouis*

2022-05-23 18:31 UTC, ZomDev3343 commented on docs/bases/resources/tags.md
> +| `has_structure\mineshaft`              | Liste des biomes pouvant contenir des mines abandonnée                 |
abandonnées*

2022-05-23 18:32 UTC, ZomDev3343 commented on docs/bases/resources/tags.md
> +| `dolphin_located`           | Liste des structure _configurées_ pouvant être localisées par un dolphin          |
remplacer dolphin par dauphin peut-être

2022-05-23 18:32 UTC, ZomDev3343 commented on docs/bases/resources/tags.md
> +| `mineshaft`                 | Listes des structures _configurées_ qui sont des puits de mine abandonné          |
abandonnée*

2022-05-23 18:33 UTC, ZomDev3343 requested changes
Faut juste rectifier quelques petites coquilles et après c'est good !

2022-05-23 18:55 UTC, merged

2022-05-23 18:57 UTC, knightmar commented on docs/bases/resources/tags.md
> +| `logs_that_burn`             | Liste des tous les types de troncs combustibles                                                  |
c'est les troncs qui peuvent prendre feu ou les troncs qui brûlent dans des fourneaux ?

2022-05-23 18:58 UTC, knightmar commented on docs/bases/resources/tags.md
> +| `non_flammable_wood`         | Liste des tous les types de bois non combustibles                                                |
pareil ici

2022-05-23 18:58 UTC, knightmar commented on docs/bases/resources/tags.md
> +| `piglin_food`                | Liste des items que mangent les plugins                                                          |
piglins et non plugins

2022-05-23 18:59 UTC, knightmar commented on docs/bases/resources/tags.md
> +| `stone_tool_materials`       | Liste des items permettant de crafter les outils et armes en roche                               |
pierre, et non roche

2022-05-23 19:00 UTC, knightmar commented on docs/bases/resources/tags.md
> +Le dossier pour ces tags est préalablement contenu dans le dossier `worldgen` qui est lui-même contenu dans le dossier `tags`
je pense que le mot "préalablement" ne sert pas a grand chose

2022-05-23 19:02 UTC, knightmar commented on docs/bases/resources/tags.md
> +| `has_structure\ruined_portal_standard` | Liste des biomes pouvant contenir des ruines de portail _standards_    |
standard sans S

2022-05-23 19:03 UTC, knightmar commented on docs/bases/resources/tags.md
> +Le dossier pour ces tags est préalablement contenu dans le dossier `worldgen` qui est lui-même contenu dans le dossier `tags`
préalablement encore

2022-05-23 19:04 UTC, knightmar commented on docs/bases/resources/tags.md
> +| `eye_of_ender_located`      | Liste des structures _configurées_ pouvant être localisées par un oeil de l'Ender |
est ce que c'est possible de mettre œil au lieu de oeil ?