Ajout d'un paragraphe pour expliquer l'ajout des items dans l'onglet créatif.
Les-Moddeurs-Francais/Documentation-Forge pull request #206
Opened 2022-09-01 09:50 UTC by knightmar

2022-09-01 10:08 UTC, Mysterious-Dev requested changes
Pour l'instant, voilà ce que je trouve à redire.

2022-09-01 10:08 UTC, Mysterious-Dev commented on docs/items/creative-tab.md
> +Ajoutez juste la méthode **.tab()** a la liste des propriétés de votre item, celle ci prends en paramètre la creativeTab crée auparavant :
Peut être m'être un lien vers la page des propriétés des items pour le mot "propriétés"

2022-09-01 10:08 UTC, Mysterious-Dev commented on docs/items/creative-tab.md
> +# Ajout des items
Passer ce titre en h2 (deux #) ainsi que les autres.

2022-09-01 10:12 UTC, knightmar commented
très bien, je fais ça quand j'ai le temps

2022-09-01 15:23 UTC, knightmar commented on docs/items/creative-tab.md
> +# Ajout des items
fait

2022-09-01 15:23 UTC, knightmar commented on docs/items/creative-tab.md
> +Ajoutez juste la méthode **.tab()** a la liste des propriétés de votre item, celle ci prends en paramètre la creativeTab crée auparavant :
fait

2022-09-01 15:32 UTC, knightmar commented
voici la nouvelle version

2022-09-01 16:09 UTC, Mireole reviewed
Je vois quelques fautes :

2022-09-01 16:09 UTC, Mireole commented on docs/items/creative-tab.md
> +Ajoutez juste la méthode **.tab()** a la liste des [propriétés](https://forge-doc.lesmoddeursfrancais.com/docs/items/properties) de votre item, celle ci prends en paramètre la creativeTab crée aupara
Je sais que je suis relou mais :

- `à la liste` et non pas `a la liste`
- `celle ci *prend* en paramètre` ?
- `la creativeTab *créée* auparavant`

2022-09-01 16:36 UTC, knightmar commented on docs/items/creative-tab.md
> +Ajoutez juste la méthode **.tab()** a la liste des [propriétés](https://forge-doc.lesmoddeursfrancais.com/docs/items/properties) de votre item, celle ci prends en paramètre la creativeTab crée aupara
non mais tu as raison, tkt

2022-09-01 16:36 UTC, knightmar commented on docs/items/creative-tab.md
> +Ajoutez juste la méthode **.tab()** a la liste des [propriétés](https://forge-doc.lesmoddeursfrancais.com/docs/items/properties) de votre item, celle ci prends en paramètre la creativeTab crée aupara
je corrige ça dès que je peux

2022-09-06 16:17 UTC, Mysterious-Dev requested changes

2022-09-06 16:17 UTC, Mysterious-Dev commented on docs/items/creative-tab.md
> +Ajoutez juste la méthode **.tab()** a la liste des [propriétés](https://forge-doc.lesmoddeursfrancais.com/docs/items/properties) de votre item, celle ci prends en paramètre la creativeTab crée aupara
```suggestion
Ajoutez juste la méthode **.tab()** a la liste des [propriétés](../items/properties) de votre item, celle ci prends en paramètre la creativeTab crée auparavant :
```

2022-09-10 14:40 UTC, Mysterious-Dev commented on docs/items/creative-tab.md
> +Ajoutez juste la méthode **.tab()** a la liste des [propriétés](https://forge-doc.lesmoddeursfrancais.com/docs/items/properties) de votre item, celle ci prends en paramètre la creativeTab crée aupara
Des nouvelles d'un changement pour cette review ?

2022-09-12 06:27 UTC, knightmar commented on docs/items/creative-tab.md
> +Ajoutez juste la méthode **.tab()** a la liste des [propriétés](https://forge-doc.lesmoddeursfrancais.com/docs/items/properties) de votre item, celle ci prends en paramètre la creativeTab crée aupara
oui, désolé, je le fais ce soir s'y j'y pense

2022-09-12 11:15 UTC, knightmar commented
c'est bon

2022-10-02 14:48 UTC, Mysterious-Dev requested changes
Voilà ce que je retrouverais à redire avant le merge

2022-10-02 14:48 UTC, Mysterious-Dev commented on docs/items/creative-tab.md
> +Ajoutez juste la méthode **.tab()** à la liste des propriétés de votre item, celle ci prend en paramètre la creativeTab créée auparavant :
```suggestion
Ajoutez juste la méthode **.tab()** à la liste des propriétés de votre item, celle-ci prend en paramètre la creativeTab créée auparavant :
```

2022-10-02 14:48 UTC, Mysterious-Dev commented on docs/items/creative-tab.md
> +Et voilà, votre item devrait être en jeu.
```suggestion
Et voilà, votre item devrait être accessible en jeu depuis le menu créatif.
```

2022-10-02 15:06 UTC, knightmar commented
ça semble bon après un peu de galère avec git :D

2022-10-02 15:08 UTC, Mysterious-Dev commented
Alors il y a le package-lock.json qui c'est glissé un moment donné. Est-il possible pour toi de le virer du PR ?

2022-10-02 15:18 UTC, closed without merging