Page Config WIP
Les-Moddeurs-Francais/Documentation-Forge pull request #223
Opened 2022-11-14 10:57 UTC by ZomDev3343

Page de doc sur les configs

2022-11-14 16:30 UTC, Mysterious-Dev commented on docs/bases/config.md
> +sidebar_position: 6
Peut-être échanger la position de cette page avec celle sur l’exportation (donc celle-ci serait en 5 et l'autre en 6).

2022-11-23 12:49 UTC, ZomDev3343 commented on docs/bases/config.md
> +sidebar_position: 6
J'ai changé dans le dernier commit

2022-11-23 12:53 UTC, Mysterious-Dev commented on docs/bases/config.md
> +Enfin, la méthode `pop` indique que l'on a terminé la configuration de notre config (ça fait beaucoup de config 🧐)
`pop` permet d'indiquer qu'une section est terminée normalement (à moins que je mélange avec autre chose).

2022-11-23 12:54 UTC, Mysterious-Dev commented on docs/bases/config.md
> +description: Ajouter une configuration à son mod
Peut-être mettre ça sous forme de question pour harmoniser avec les autres pages.

2022-11-23 15:10 UTC, knightmar commented
ça me paraît bien

2022-11-24 18:05 UTC, Mysterious-Dev commented on docs/bases/config.md
> +valeur par défaut.
```suggestion
La méthode `define` prend deux paramètres : le nom affiché dans la config (ici `"guiOnDeath"`) et sa
valeur par défaut (ici `true`).
```

Dis moi ce que tu en pense (suggestion ouverte)

2022-11-24 18:27 UTC, Mysterious-Dev requested changes
Je vois déjà ça. Une fois corrigé, attend mon approbation pour le merge car il reste des choses (qu'il faut que je vérifie).

2022-11-24 18:27 UTC, Mysterious-Dev commented on docs/bases/config.md
> +### Classe de configuration
Pourquoi mettre ça en h3 ?

2022-11-24 18:27 UTC, Mysterious-Dev commented on docs/bases/config.md
> +## Client
Avec le commentaire précédent, mettre ça en h2 ?

2022-11-24 18:27 UTC, Mysterious-Dev commented on docs/bases/config.md
> +### Server
Pourquoi mettre ça en h3 alors que `Client` est en h2 ?

2022-11-24 18:27 UTC, Mysterious-Dev commented on docs/bases/config.md
> +### Common
Pourquoi mettre ça en h3 alors que `Client` est en h2 ?

2022-11-24 18:27 UTC, Mysterious-Dev commented on docs/bases/config.md
> +### Enregistrement
Du coup, ça serait plus en h2 (pour différencier avec la configuration de la classe) ?

2022-11-24 18:27 UTC, Mysterious-Dev commented on docs/bases/config.md
> +### Utilisation dans le code
Même chose que pour `Enregistrement`.

2022-11-25 13:17 UTC, ZomDev3343 commented on docs/bases/config.md
> +valeur par défaut.
J'avoue c'est mieux formulé 👍

2022-11-25 13:30 UTC, ZomDev3343 commented on docs/bases/config.md
> +### Utilisation dans le code
Petites coquilles, j'ai du oublier que j'avais mis des h2 et non des h3

2022-11-25 13:39 UTC, Mysterious-Dev commented on docs/bases/config.md
> +## Common
```suggestion
### Common
```

2022-11-25 13:39 UTC, Mysterious-Dev commented on docs/bases/config.md
> +## Server
```suggestion
### Server
```

2022-11-25 13:39 UTC, Mysterious-Dev commented on docs/bases/config.md
> +## Client
```suggestion
### Client
```

2022-11-25 13:46 UTC, Mysterious-Dev commented on docs/bases/config.md
> +```
Je n'arrive pas vraiment à comprendre l'intéret de l'utilisation de l'objet Pair en soit.

https://github.com/Mysterious-Dev/Test-Mod-Forge/blob/1.19.x/src/main/java/fr/lmf/test_mod_forge/utils/ModConfig.java
https://github.com/Mysterious-Dev/Test-Mod-Forge/blob/1.19.x/src/main/java/fr/lmf/test_mod_forge/Main.java#L64

2022-11-25 13:48 UTC, Mysterious-Dev commented on docs/bases/config.md
> +```
My bad, y'a les deux manière de faire. Ca paraitr plus "propre" cette solution.

2022-11-25 13:50 UTC, Mysterious-Dev commented on docs/bases/config.md
> +modLoadingContext.registerConfig(net.minecraftforge.fml.config.ModConfig.Type.COMMON, ModConfig.commonSpec, configFolder + "common.toml");
Peut-être montrer qu'il est aussi possible d'enregistrer une config sans donner de paramètre `fileName`.

2022-11-25 13:50 UTC, Mysterious-Dev commented on docs/bases/config.md
> +Désormais si vous lancez le jeu, dans le dossier config du monde vous aurez un dossier avec vos configs à l'intérieur où
Peut-être mettre un résultat (screenshot) des fichiers générés ?

2022-12-01 20:50 UTC, Mysterious-Dev approved these changes

2022-12-01 20:51 UTC, merged