Resources pages & category
Les-Moddeurs-Francais/Documentation-Forge pull request #72
Opened 2021-12-30 10:05 UTC by Mysterious-Dev

2022-01-04 19:38 UTC, Romaindu35 approved these changes

2022-01-06 15:11 UTC, ZomDev3343 commented on docs/bases/resources/index.md
> +Les modèles sont définies par des fichiers JSON.
définis

2022-01-06 15:12 UTC, ZomDev3343 commented on docs/bases/resources/index.md
> +Les tables de butin sont définis par des fichiers JSON se trouvant dans le dossier `/data/<modid>/loot_tables` (des sous dossiers sont attendus selon si cela concerne les blocs (`blocks`), les coffre
définies

2022-01-06 15:13 UTC, ZomDev3343 requested changes
A part quelques erreurs d'accords, on est bon

2022-01-06 15:18 UTC, merged